### ISSUE TITLE
You're username AKA Email is case Sensitive

### ISSUE THREAD

**Issue by LkingForW** [UPE-FIU/Shell#102]
I believe what may be going in is that you're probably making the email all lowercase web the person signs-up. However when the user puts in their email for log in its does not make it lowercase, causing a database authentication issue. This could be fixed with a simple function call. 
Example: 
Apere982@fiu.edu is what I signed up with but it gets turned to -> apere982@fiu.edu
So when I put Apere982@fiu.edu **The A is capitalized ** , the authentication does not work. 

I am terrible at explaining things so I hope that this helps. For further questions email Apere982@fiu.edu.

**Comment by Jehfkemsy** [comment]
Hey, we appreciate you for taking the time to report this issue. Our dev team was able to fix it today.
