### ISSUE TITLE
Required Checkbox at the end of Application Form

### ISSUE THREAD

**Issue by henleygarcia** [UPE-FIU/Shell#115]
Good morning I was filling out the Shell Hacks application and noticed that the last checkbox was required. What if someone doesn't want to receive emails from ShellHacks? I think it should be totally optional.

**Comment by Jehfkemsy** [comment]
Hey @henleygarcia ,  thanks for reporting this ... our team will look into it and decide on whether it should be optional.
thanks again.

**Comment by Jehfkemsy** [comment]
I'm gonna close this for now, but let me know if you have any further concerns.
